::--------------------------- PING CHECKLIST ---------------------------------------------- 
@ECHO OFF &SETLOCAL ENABLEDELAYEDEXPANSION &Break OFF
REM VARIABLES DEFINITION

:VARIABLES
	SET IEL=if errorlevel GTR
	SET IND=IF NOT DEFINED
	SET IEX=if exist
	SET DIRECTORY=C:\Results
	
	REM PROCESS TO SAVE THE DATE AS DD.MM.YYYY WITHOUT THE Slash "/", BECAUSE IT WOULD GENERATE ERROR WHILE SAVING THE TXT NAME
	SET MONTH=%date:~3,2%
		if "%MONTH:~0,1%" == " " SET MONTH=0%MONTH:~1,1%
	SET DAY=%date:~0,2%
		if "%DAY:~0,1%" == " " SET DAY=0%DAY:~1,1%
	SET DTDATE=%DAY%.%MONTH%.%DATE:~6,4%
	SET HOUR=%time:~0,2%
		if "%HOUR:~0,1%" == " " SET HOUR=0%HOUR:~1,1%
	SET MIN=%time:~3,2%
		if "%MIN:~0,1%" == " " SET MIN=0%MIN:~1,1%
	SET DTTIME=%HOUR%.%MIN%
	SET DTINFO=%DTDATE%-%DTTIME%hs
		
::---------------------------DIRECTORY CHECK--------------------------------

:DIRECTORY_OK
	%IEX% "%DIRECTORY%" GOTO Checking
		) ELSE (
			cd /
			mkdir Results
			cd Results
			cls
			%IEX% "%DIRECTORY%" GOTO Checking
			) ELSE (
				SETLOCAL
					chcp 65001
						MSG * SOMETHING IS MAKING IT IMPOSSIBLE TO CREATE %DIRECTORY%, VERIFY!
				ENDLOCAL		
			EXIT
		)

::###########################################################################################################
REM CREATE A TXT FILE FOR TECHNICIAN CONTROL

:Checking
	chcp 65001
		MSG *  A FILE WILL BE CREATED IN "%DIRECTORY%\CHECKLIST %DTINFO%.txt"


:PING_CHECK
	REM FILL IN THE SAME IPS ENTERED ABOVE ( > TO CREATE >> TO ADD CONTENT) 
	@ECHO ON
	ping 192.168.0.1 > "%DIRECTORY%/CHECKLIST %DTINFO%.txt"
	Ping 192.168.0.2 >> "%DIRECTORY%/CHECKLIST %DTINFO%.txt"
	ping 192.168.0.3 >> "%DIRECTORY%/CHECKLIST %DTINFO%.txt"
	ping 192.168.0.4 >> "%DIRECTORY%/CHECKLIST %DTINFO%.txt"
	%IEX% "%DIRECTORY%\CHECKLIST %DTINFO%.txt" GOTO CHECK_SUC
		) ELSE (
			chcp 65001
				MSG * SOMETHING IS MAKING IT IMPOSSIBLE TO CREATE "CHECKLIST %DTINFO%.txt" FILE!
			GOTO OPC_CHECK
		)	
:CHECK_SUC
	@ECHO OFF
	SETLOCAL
		chcp 65001
			MSG * THE "%DIRECTORY%/CHECKLIST %DTINFO%.txt" FILE HAS BEEN CREATED!
		GOTO EXIT_CHECK
	ENDLOCAL

:OPC_CHECK
	@ECHO OFF
	SET /P OPCCHECK="TRY AGAIN? (Y/N):":
		%IEL% 0 GOTO OPC_CHECK
		%IND% OPCCHECK GOTO OPC_CHECK
		IF %OPCCHECK% == Y GOTO PING_CHECK
		IF %OPCCHECK% == y GOTO PING_CHECK
		IF %OPCCHECK% == n GOTO EXIT_CHECK
		IF %OPCCHECK% == N GOTO EXIT_CHECK
			) ELSE (
				SETLOCAL
					chcp 65001
						MSG * INCORRECT OPTION, TRY AGAIN!
					GOTO OPC_CHECK
				ENDLOCAL	
			)

:EXIT_CHECK
	@ECHO OFF
		CLS
		SETLOCAL
			chcp 65001
				MSG * %USERNAME% THANKS TO USE THIS TOOL!
		ENDLOCAL
	EXIT

	